<?php 
	unset($_SESSION['variable']);
  $pageTitle = "Login";
?>

<section class="page-section" id="connexion">
  <div class="container">
      <div class="row">
        <div class="col-lg-12">
            <form id="form" method="POST" action="" enctype="multipart/form-data" novalidate="novalidate">
              <div class="row">
                  <div class="col-md-3"></div>
                  <div class="col-md-6 login-form">
                    <div class="col-lg-12">
                        <h2 class="section-heading text-center">Login</h2>  
                        <div class="form-group">
                            <label class="label-input">Pseudo :</label>
                            <input class="form-control" id="login" name="login" type="text" required="required" data-validation-required-message="Veuillez entrer votre pseudo *" data-validation-regex-regex="^[a-z-_]*" data-validation-regex-message="Caractères non valide *">
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group">
                            <label class="label-input">Mot de passe :</label>
                            <input class="form-control text-lowercase" id="motDePasse" name="motDePasse" type="password" required="required" data-validation-required-message="Veuillez entrer votre mot de passe *">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="col-lg-12 text-center">
                      <button type="submit" class="btn btn-primary btn-xl">Connecter</button>
                      <a href="#" data-toggle="modal" data-target="#inscriptionModal">
                        <button class="btn btn-warning btn-xl">Créer compte </button>
                      </a>
                    </div>
                </div>
              </div>
            </form>
        </div>
      </div>
  </div>
</section>

 <!-- Modal -->
<div class="modal fade" id="inscriptionModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <h4>Vous voulez s'inscrire en tant que :</h4>
        <label class="container">Entreprise
          <input type="radio" name="radio" id="entreprise" value="entreprise">
          <span class="checkmark"></span>
        </label>
        <label class="container">Candidat
          <input type="radio" name="radio" id="candidat" value="candidat">
          <span class="checkmark"></span>
        </label>
        <label class="text-center hidden" id="warning">Veuillez choisir un type d'utilisateur</label>
      </div>
      <div class="modal-footer">
        <a id="inscrire"><button class="btn btn-success">Valider</button></a>
        <button type="button" class="btn btn-danger" id="annuler" data-dismiss="modal">Annuler</button>
      </div>
    </div>
  </div>
</div>

<script src="<?= HOST; ?>../Web/Ressources/js/connecter.js"></script>
