<?php
	$pageTitle = "Création d'un compte";
  if (isset($_SESSION['compte'])) {
    header("Location:" . HOST . "manage/" . $_SESSION['compte']['identifiant'] . "/dashboard");
  }
?>
<section class="page-section" id="create-compte">
  <div class="container">
  		<div class="row">
          	<div class="col-lg-12 text-center">
                <h2 class="section-heading text-uppercase">Créer compte <?= $_GET['identifiant']; ?></h2>
          	</div>
        </div>
      <div class="row">
        <div class="col-lg-12">
            <form id="form" method="POST" action="" enctype="multipart/form-data" novalidate="novalidate">
              <div class="row">
                  <div class="col-md-3"></div>
                  <div class="col-md-6 create-compte-form">
                    <div class="col-lg-12">  
                        <div class="form-group hidden">
                            <input class="form-control" id="idCompte" name="idCompte" type="number" >
                        </div>
                        <div class="form-group hidden">
                            <input class="form-control" id="identifiant" name="identifiant" type="text" value="<?= $_GET['identifiant']; ?>" readonly>
			                <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group">
                            <i class="fas fa-user-circle icon-input"></i>
                            <input class="form-control text-lowercase" id="login" name="login" type="text" required="required" data-validation-required-message="Veuillez entrer votre pseudo *" data-validation-regex-regex="^[a-z-_]*" data-validation-regex-message="Caractères non valide *" placeholder="Pseudo">
			                <p class="help-block text-danger" id="login-message"></p>
                        </div>   
                        <div class="form-group">
                            <i class="fas fa-lock icon-input"></i>
                            <input class="form-control" id="motDePasse" name="motDePasse" type="password" required="required" data-validation-required-message="Veuillez entrer votre mot de passe *" data-validation-regex-regex="^.{6,}$" data-validation-regex-message="6 caractères minimum *" placeholder="Mot de passe">
			                <p class="help-block text-danger" id="length-message"></p>
                        </div>   
                        <div class="form-group">
                          <i class="fas fa-key icon-input"></i>
                            <input class="form-control" id="confirmation" name="confirmation" type="password" required="required" data-validation-required-message="Veuillez confirmer votre mot de passe *" placeholder="Confirmation du mot de passe">
			                <p class="help-block text-danger" id="match-message"></p>
                        </div>   
                        <div class="form-group hidden">
                            <input class="form-control" id="statut" name="statut" type="text" value="active" required="required">
                        </div> 
                    </div>
                    <div class="col-lg-12 text-center">
                      	<button id="submit" class="btn btn-warning btn-xl" type="submit">
                			Suivant
			            	<i class="fas fa-angle-double-right fa-inverse"></i>
                		</button>
                    </div>
                </div>
              </div>
            </form>
        </div>
      </div>
  </div>
</section>

<script src="<?= HOST; ?>../Web/Ressources/js/creerCompte.js"></script>

