<?php
	$pageTitle = "Spécification des personnalités";
	extract($data);
?>
<section class="page-section" id="back-section">
    <div class="container">
    	<div class="row">
	        <ul id="tab-button">
        		<li id="a"><a href="<?= HOST. "manage/edit-candidat?idCandidat=" . $_SESSION['user']['idCandidat'];?>">Modifier profil</a></li>
			    <li id="b"><a href="<?= HOST . 'manage/update-password?idCompte=' . $_SESSION['compte']['idCompte']; ?>">Modifier mot de passe</a></li>
			    <li id="c"><a href="<?= HOST . 'manage/edit-pseudo?idCompte=' . $_SESSION['compte']['idCompte']; ?>">Modifier Pseudo</a></li>
			    <li id="d"><a href="<?= HOST . "manage/edit-personnalite_candidat?idCandidat=" . $_SESSION['user']['idCandidat']; ?>">Modifier personnalité</a></li>
	        </ul>
      	</div>
	    <div class="row">
    		<form id="form" method="POST" name="form" action="<?= HOST . "manage/save-candidat" ?>" enctype="multipart/form-data">
	        	<div class="row">
	        		<div class="col-md-6 block-div">
	        		<div class="form-group hidden">
						<input class="form-control" type="number" name="idCandidat" value="<?= $candidat->getIdCandidat(); ?>" />
					</div> 
					<div class="form-group hidden">
						<input class="form-control" type="text" name="personnalite" id="personnalite" />
					</div>
					<label class="label-input">Trait de personnalité :</label>
					<div class="form-group trait-personnalite">
						<?php foreach($personnalites as $personnalite):?>
							<label class="text-left"> 
							  <input type="checkbox" name="qualite" value="<?= $personnalite->getQualite(); ?>" class="qualite" 
							  <?php
							  	$persos = explode('_', $candidat->getPersonnalite());
				                foreach ($persos as $perso) {
				                  if ($personnalite->getQualite() == ucfirst($perso)) {
				                  	echo "checked";
				                  }
				                }
							  ?>
							  >
							  <?= $personnalite->getQualite(); ?>
							</label><br>
						<?php endforeach; ?>
					</div>
	        	</div>								  
                <div class="col-md-5 block-div">
                	<div class="form-group">
						<input class="btn btn-warning" type="button" value="Ajouter une autre personnalité" id="autre" >
						<input class="form-control hidden" id="autrePersonnalite" name="autrePersonnalite" type="text">
					</div>
					<div class="form-group" id="block-personnalite"></div>
                </div>
                <div class="col-lg-12 text-center">
					<button class="btn btn-info btn-xl" type="submit" id="submit"> 
				    	Enregistrer
				    </button>
		            <a class="btn btn-danger btn-xl" href="<?= HOST . 'manage/' . $_SESSION['compte']['identifiant'] . '/dashboard'; ?>">Annuler</a>
              	</div> 
	        	</div>	
	        </form>
	    </div>
    </div>
</section>

<script src="<?= HOST; ?>../Web/Ressources/js/afficherFormPersonnalite.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/tabCandidat.js"></script>