<?php
	$pageTitle = "Modification du mot de passe";
?>
<section class="page-section" id="back-section">
    <div class="container">
    	<div class="row">
	        <ul id="tab-button">
	        	<?php if ($_SESSION['compte']['identifiant'] == "candidat"): ?>
	        		<li id="a"><a href="<?= HOST. "manage/edit-candidat?idCandidat=" . $_SESSION['user']['idCandidat'];?>">Modifier profil</a></li>
				    <li id="b"><a href="<?= HOST . 'manage/update-password?idCompte=' . $_SESSION['compte']['idCompte']; ?>">Modifier mot de passe</a></li>
				    <li id="c"><a href="<?= HOST . 'manage/edit-pseudo?idCompte=' . $_SESSION['compte']['idCompte']; ?>">Modifier Pseudo</a></li>
				    <li id="d"><a href="<?= HOST . "manage/edit-personnalite_candidat?idCandidat=" . $_SESSION['user']['idCandidat']; ?>">Modifier personnalité</a></li>
	        	<?php elseif ($_SESSION['compte']['identifiant'] == "entreprise"): ?>
	        		<li id="d"><a href="<?= HOST. "manage/edit-entreprise?idEntreprise=" . $_SESSION['user']['idEntreprise'];?>">Modifier profil</a></li>
				    <li id="e"><a href="<?= HOST . 'manage/update-password?idCompte=' . $_SESSION['compte']['idCompte']; ?>">Modifier mot de passe</a></li>
				    <li id="f"><a href="<?= HOST . 'manage/edit-pseudo?idCompte=' . $_SESSION['compte']['idCompte']; ?>">Modifier Pseudo</a></li>
				<?php elseif ($_SESSION['compte']['identifiant'] == "superadmin"): ?>	        		
				    <li id="a"><a href="<?= HOST . "manage/edit-superadmin?idSuperadmin=" . $_SESSION['user']['idSuperadmin']?>">Modifier profil</a></li>
				    <li id="b"><a href="<?= HOST . 'manage/update-password?idCompte=' . $_SESSION['compte']['idCompte']; ?>">Modifier mot de passe</a></li>
				    <li id="c"><a href="<?= HOST . 'manage/edit-pseudo?idCompte=' . $_SESSION['compte']['idCompte']; ?>">Modifier pseudo</a></li>
	        	<?php endif ?>
	        </ul>
      	</div>
      	<div class="row">
        	<div class="col-lg-12">
          		<form id="form" method="POST" enctype="multipart/form-data" enctype="multipart/form-data" novalidate="novalidate">
		            <div class="row">
		            	<div class="col-md-4"></div>
		              	<div class="col-md-4 block-div">
			                <div class="form-group">
			                	<label class="label-input">Mot de passe actuel :</label>
			                  	<input class="form-control focus_activated" id="ancienMotDePasse" name="ancienMotDePasse" type="password" required="required" data-validation-required-message="Veuillez entrer votre mot de passe actuel *">
			                  	<p class="help-block text-danger"></p>
			                </div>
			                <div class="form-group">
			                	<label class="label-input">Nouveau mot de passe :</label>
			                  	<input class="form-control focus_activated" id="motDePasse" name="motDePasse" type="password" required="required" data-validation-required-message="Veuillez entrer votre nouveau mot de passe *"  data-validation-regex-regex="^.{6,}$" data-validation-regex-message="6 caractères minimum *">
			                  	<p class="help-block text-danger"></p>
			                </div>
			                <div class="form-group">
			                	<label class="label-input">Confirmation du nouveau mot de passe :</label>
			                  	<input class="form-control focus_activated" id="confirmation" name="confirmation" type="password" required="required" data-validation-required-message="Veuillez confirmer votre nouveau mot de passe.">
			                  	<p class="help-block text-danger" id="match-message"></p>
			                </div>
			                <div class="col-lg-12 text-center">
			                	<button id="submit" class="btn btn-info btn-xl" type="submit">
			                		Enregistrer
			                	</button>
			                	<a class="btn btn-danger btn-xl" href="<?= HOST . 'manage/' . $_SESSION['compte']['identifiant'] . '/dashboard'; ?>">Annuler</a>
			              	</div> 
		              	</div>
		            </div>
          		</form>
        	</div>
      	</div>
    </div>
</section>

<script src="<?= HOST; ?>../Web/Ressources/js/creerCompte.js"></script>
<?php if ($_SESSION['compte']['identifiant'] == "candidat"): ?>
	<script src="<?= HOST; ?>../Web/Ressources/js/tabCandidat.js"></script>
<?php elseif ($_SESSION['compte']['identifiant'] == "entreprise"): ?>
	<script src="<?= HOST; ?>../Web/Ressources/js/tabEntreprise.js"></script>
<?php elseif ($_SESSION['compte']['identifiant'] == "superadmin"): ?>
	<script src="<?= HOST; ?>../Web/Ressources/js/tabSuperadmin.js"></script>
<?php endif ?>
