<?php
	$pageTitle= "Accueil";
?>
<!-- Header -->
    <header class="masthead">
        <div class="container">
            <div class="intro-text">
              <div class="intro-lead-in">Bienvenue sur le site 
                <img class="rounded-circle img-fluid" id="smile" src="<?= HOST; ?>../Web/Ressources/images/smile.jpg">
              </div>
              <div class="intro-heading text-uppercase">
                Human Cart'<img class="rounded-circle img-fluid" id="office" src="<?= HOST; ?>../Web/Ressources/images/logowebsite.png">ffice
              </div>
              <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="<?= HOST;?>accueil#a-propos">A propos de HCO</a>
            </div>
        </div>
      </header>
      <section class="bg-light page-section" id="a-propos">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center">
              <h2 class="section-heading text-uppercase">Qui sommes nous?</h2>
              <h3 class="section-subheading text-muted">
                    Human Cart’Office est créé depuis le mois de mars 2013.<br>
              Le développement personnel et le plaisir que chacun met en œuvre pour collaborer ensemble sont les notions premières qui constituent notre société.<br>
              Nous sommes prestataires de service en ressources humaines et juridiques.<br>
              Notre société adopte une approche pragmatique pour aider nos clients à passer un projet ou une activité d’un modèle latent à un modèle plus dynamique à travers un savoir-faire et une expertise très poussées..
              </h3>
            </div>
          </div>
          <div class="row text-center">
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                  <i class="fas fa-circle fa-stack-2x text-primary"></i>
                  <i class="fab fa-accusoft fa-stack-1x fa-inverse"></i>
                </span>
              <h4 class="service-heading">Nos atouts</h4>
              <p class="text-muted">+ 350 missions validées</p>
              <p class="text-muted">Taux de croissance constante de +45% du CA (2013 à 2018)</p>
              <p class="text-muted">Système d’information des ressources humaines en partenariat avec Medialibs Nantes.</p>
              <p class="text-muted">Une moyenne de 80 postes par an en recrutement</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                  <i class="fas fa-circle fa-stack-2x text-primary"></i>
                  <i class="fas fa-book-open fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">Nos engagements</h4>
                <p class="text-muted">Nous vous accompagnons dans la performance et dans un esprit de Co création.</p>
                <p class="text-muted">Nous adaptons nos offres aux besoins de nos clients. Que vous soyez une jeune entreprise ou une société expérimentée, HCO apporte son savoir-faire pour répondre le plus justement à vos exigences.</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                  <i class="fas fa-circle fa-stack-2x text-primary"></i>
                  <i class="fas fa-grin-stars fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">Nous CHOISIR</h4>
                <p class="text-muted">1- Competénces</p>
                <p class="text-muted">2- Efficacités</p>
                <p class="text-muted">3- Prix compétitifs</p>
                <p class="text-muted">4- Confidentialité</p>
                <p class="text-muted">5- Support client complet</p>
            </div>
          </div>
        </div>
     </section>

     <section class="page-section" id="activites">
        <div class="container">
            <div class="row">
              <div class="col-lg-12 text-center">
                  <h2 class="section-heading text-uppercase">Nos Activités</h2>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12">
                  <ul class="">
                    <li>
                        <div class="timeline-panel">
                          <div class="timeline-heading">
                              <h4 class="subheading">Recrutement</h4>
                          </div>
                        <div class="timeline-body">
                            <p class="text-muted">
                              Nous sommes l’un des prestataires en recrutement qui propose un « short-list » de candidat dont le rapport d’évaluation démontre clairement les adéquations profil/poste et la technicité au poste.<br>
                      Selon le type de mission, nous sommes emmenées à chasser le bon profil au niveau national et parfois au niveau international.<br>
                      Nous sommes en partenariat avec des structures internationales à l’ile Maurice, dans les pays du Maghreb…pour recevoir des candidats expatriés.<br>
                      Notre système d’évaluation psychologique reflète la personnalité, la motivation et le raisonnement de nos candidats.
                            </p>
                        </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-panel">
                          <div class="timeline-heading">
                              <h4 class="subheading">Evaluation</h4>
                          </div>
                          <div class="timeline-body">
                              <p class="text-muted">
                                Avez-vous été comme nous?<br>
                      Nous avons tout fait pour réussir nos recrutements. Nous avons commencé par bien trier les CVs et les candidatures qui parvenaient à nous
                      =>ce n'était pas suffisant.<br>
                      Nous avons optimisé encore plus en faisant passer des tests, réaliser des mises en situation etc...
                      =>nous n’étions toujours pas satisfaits de nos résultats en recrutement.<br>
                      Nous avons poussé notre recherche de satisfaction en mettant en place une analyse psychologique de la personnalité pour une meilleure mise en adéquation du profil / poste
                      => le résultat nous semblait déjà meilleur, mais pas assez !<br>
                      Aujourd’hui nous avions réussi à mettre en place un "matching" entre l’adéquation de la personnalité des (futurs) collaborateurs avec celle de leurs (futurs) managers<br>
                      LE RESULTAT EST PARFAIT<br>
                      Vous aussi, confier vos recrutements à un professionnel ou demander une évaluation auprès de notre service client
                              </p>
                          </div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-panel">
                          <div class="timeline-heading">
                              <h4 class="subheading">Administration</h4>
                          </div>
                          <div class="timeline-body">
                              <p class="text-muted">
                                Ce service permet à toute entreprise et société d’externaliser la gestion opérationnelle, décisionnelle et stratégique de ses ressources humaines.<br>
                      Nous sommes tous conscients que les informations relatives à vos ressources humaines doivent demeurer confidentielles. Dans la pratique, l’entreprise supporte des coûts non négligeables dans le maintien d’une équipe RH, avec son cadre dirigeant, alors que les opérations administratives, orientations stratégiques, contrôles et nouveaux processus pourraient être externalisés. Cette orientation d’externalisation du département RH, nécessite le pouvoir social des managers sur l’ensemble de leur équipe respective.<br>
                      Ce service HCO comprend la gestion administrative générale (mise en place d’un manuel de procédure RH, paie, organismes sociaux et étatiques, gestion des contrats de travail, gestion des congés et repos maladies…)<br>
                      Les conseils juridiques RH sont également intégrés dans ce service. Néanmoins, la représentation judiciaire devant les instances sociales fera l’objet d’une nouvelle facturation forfaitaire (demandez un devis).
                              </p>
                          </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-panel">
                          <div class="timeline-heading">
                              <h4 class="subheading">SIRH</h4>
                          </div>
                          <div class="timeline-body">
                              <p class="text-muted">
                                La digitalisation est devenue incontournable pour le développement d’une entreprise.<br>
                      Un SIRH serait un atout majeur pour le management en général et le développement en particulier.<br>
                      Un SIRH :<br>
                      <ul class="text-muted">
                        <li> réduit spectaculairement les charges de travail, </li>
                        <li> minimise les risques d’erreur, </li>
                        <li> fluidifie les échanges </li>
                        <li> améliore la qualité des données et de base de données </li>
                        <li> fait gagner en temps et en argent </li>
                        <li> permet d’anticiper les besoins </li>
                        <li> gère au mieux le budget </li>
                        <li> améliore le processus interne </li>
                      </ul>                 
                              </p>
                          </div>
                        </div>
                    </li>
                  </ul>
              </div>
            </div>
        </div>
     </section>
     <section class="page-section" id="contact">
        <div class="container">
            <div class="row">
              <div class="col-lg-12 text-center">
                <h2 class="section-heading text-uppercase">Contactez-nous</h2>
                <label class="">
                  Coordonnées :
                  <p >
                  Près logt 19 Cité Gallois Ouest Ambohijanary</br>
                  Tél : +261 20 22 281 02</br>
                  E-mail : ourrecrut@gmail.com</br>
                  Heures d'ouverture : Lundi à Vendredi 08h30 à 17h</br>
                  </p>
                </label>              
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12">
                  <form id="form" method="POST" action="<?= HOST. "send_message";?>" enctype="multipart/form-data" novalidate="novalidate">
                    <div class="row">
                        <div class="col-md-6">
                          <div class="form-group">
                              <input class="form-control text-uppercase" id="nom" name="nom" type="text" placeholder="Votre Nom " required="required" data-validation-required-message="Veuillez entrer votre nom *" data-validation-regex-regex="^[a-zA-Z'éèêëôöîïàç ]*" data-validation-regex-message="Caractères non valide *">
                              <p class="help-block text-danger"></p>
                          </div>
                          <div class="form-group">
                              <input class="form-control text-capitalize" id="prenom" name="prenom" type="text" placeholder="Votre Prénom"  data-validation-regex-regex="^[a-zA-Z'éèêëôöîïàç ]*" data-validation-regex-message="Caractères non valide *">
                          </div>
                          <div class="form-group">
                              <input class="form-control" id="phone" name="phone" type="number" placeholder="Votre téléphone" required="required" data-validation-required-message="Veuillez entrer votre téléphone *"data-validation-regex-regex="[0-9]{10}" data-validation-regex-message="10 Chiffres">
                              <p class="help-block text-danger"></p>
                          </div>
                          <div class="form-group">
                              <input class="form-control text-lowercase" id="email" name="email" type="email" placeholder="Votre email " required="required" data-validation-required-message="Veuillez entrer votre e-mail *">
                              <p class="help-block text-danger"></p>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                              <textarea class="form-control" id="message" name="message" placeholder="Votre message" required="required" data-validation-required-message="Veuillez entrer votre message *"></textarea>
                              <p class="help-block text-danger"></p>
                          </div>
                        </div>
                        <div class="col-lg-12 text-center">
                          <button class="btn btn-primary btn-xl js-scroll-trigger" type="submit">Envoyer ...</button>
                        </div>
                    </div>
                  </form>
              </div>
            </div>
        </div>
    </section>
