<!DOCTYPE html>
<html lang="en">
	<head>
  		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  		<title><?= $pageTitle; ?></title>

		<link rel="stylesheet" type="text/css" href="<?= HOST; ?>../Web/Ressources/css/plugin/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="<?= HOST; ?>../Web/Ressources/css/fontawesome-free/css/all.min.css">	
		<link rel="stylesheet" type="text/css" href="<?= HOST; ?>../Web/Ressources/css/plugin/agency.min.css">			
		<link rel="stylesheet" type="text/css" href="<?= HOST; ?>../Web/Ressources/css/plugin/datepicker.css">	
 		<link rel="stylesheet" type="text/css" href="<?= HOST; ?>../Web/Ressources/css/style.css">

 		<!-- Fonts CDN -->
		<link rel="stylesheet" type="text/css" href="<?= HOST; ?>../Web/Ressources/css/plugin/fonts/montserrat.css">
		<link rel="stylesheet" type="text/css" href="<?= HOST; ?>../Web/Ressources/css/plugin/fonts/kaushan.css">
		<link rel="stylesheet" type="text/css" href="<?= HOST; ?>../Web/Ressources/css/plugin/fonts/serif.css">
		<link rel="stylesheet" type="text/css" href="<?= HOST; ?>../Web/Ressources/css/plugin/fonts/roboto.css">

		<script src="<?= HOST; ?>../Web/Ressources/js/plugin/jquery.min.js"></script>
		<script src="<?= HOST; ?>../Web/Ressources/js/plugin/jquery.easing.min"></script>
		<script src="<?= HOST; ?>../Web/Ressources/js/plugin/bootstrap.bundle.min"></script>
		<script src="<?= HOST; ?>../Web/Ressources/js/plugin/jqBootstrapValidation.js"></script>
		<script src="<?= HOST; ?>../Web/Ressources/js/plugin/filter.js"></script>	
		<script src="<?= HOST; ?>../Web/Ressources/js/plugin/agency.min.js"></script>				
		<script src="<?= HOST; ?>../Web/Ressources/js/plugin/datepicker.js"></script>		  

	</head>
	<body>
		<!-- Navigation -->
		<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    		<div class="container">
      			<a class="navbar-brand js-scroll-trigger" href="<?= HOST;?>accueil">Human Cart'Office</a>
			    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			        Menu
			    <i class="fas fa-bars"></i>
			    </button>
      			<div class="collapse navbar-collapse" id="navbarResponsive">
			        <ul class="navbar-nav text-uppercase ml-auto">
			          	<li class="nav-item">
			            	<a class="nav-link js-scroll-trigger" href="<?= HOST;?>accueil">
			            	<i class="fas fa-home"></i>
			            	</a>
			          	</li>
			          	<li class="nav-list nav-item">
			            	<a class="nav-link js-scroll-trigger" href="#">A propos</a>
		                	<ul class="list text-lowercase">
		                    	<li><a href="<?= HOST;?>accueil#a-propos">Qui somme-nous?</a></li>
		                    	<li><a href="<?= HOST;?>accueil#activites">Nos activités</a></li>
		                	</ul>
			          	</li>
			          	<li class="nav-item">
			            	<a class="nav-link js-scroll-trigger" href="<?= HOST;?>accueil#contact">
			            	Contact
			            	</a>
			          	</li>
			          	<li class="nav-item">
			            	<a class="nav-link js-scroll-trigger" href="<?= HOST;?>offres">
			            	Offres
			            	</a>
			          	</li>
			          	<?php if (isset($_SESSION['compte'])): ?>			          		
				          	<li class="nav-list nav-item">
			            	<a class="nav-link js-scroll-trigger text-uppercase" href="#">Mon compte</a>
		                	<ul class="list text-lowercase">
		                    	<li><a href="<?= HOST . 'manage/' . $_SESSION['compte']['identifiant'] . '/dashboard';?>">Profil</a></li><hr>		                    	
		                    	<li><a href="<?= HOST;?>deconnexion">Deconnexion</a></li>
		                	</ul>
			          	</li>
				        <?php else: ?>	
				        	<li class="nav-list nav-item">
				            	<a class="nav-link js-scroll-trigger" href="#">S'inscrire</a>
			                	<ul class="list text-lowercase">
			                    	<li><a href="<?= HOST; ?>create-compte?identifiant=candidat">Candidat</a></li>
			                    	<li><a href="<?= HOST; ?>create-compte?identifiant=entreprise">Entreprise</a></li>
			                	</ul>
				          	</li>
				          	<li class="nav-item">
				            	<a class="nav-link js-scroll-trigger" href="<?= HOST;?>connexion">
				            	Se connecter
				            	</a>
				          	</li>	
			          	<?php endif ?>
			        </ul>
      			</div>
    		</div>
  		</nav>
		<div id="content-page">
			<?= $pageContent; ?>
		</div>
		<div class="container">
			<?php if (isset($_SESSION['info'])) {
	   			foreach ($_SESSION['info'] as $type => $message) {
					echo "<div class='info container alert alert-" . $type . "' data-dismiss='alert' id='alert'>" . $message . "</div>";
					unset($_SESSION['info']);		
				}
	    	}?>
		</div>
		<footer class="footer">
		    <div class="container">
		      <div class="row align-items-center">
		        <div class="col-md-4">
		          <span class="copyright">Copyright &copy; Your Website 2019</span>
		        </div>
		        <div class="col-md-4">
		          <ul class="list-inline social-buttons">
		            <li class="list-inline-item">
		              <a href="#">
		                <i class="fab fa-facebook-f"></i>
		              </a>
		            </li>
		          </ul>
		          <label class="">
	                Coordonnées :
	                <p >
	                Tél. : +261 20 22 281 02</br>
	                E-mail : ourrecrut@gmail.com</br>
	                </p>
	              </label>
		        </div>
		        <div class="col-md-4">
		          <a href="#" class="text-footer">
	              	<h4>Human Cart'Office</h4>
	              </a>
		        </div>
		      </div>
		    </div>
		</footer>
	</body>
</html>

<script src="<?= HOST; ?>../Web/Ressources/js/header.js"></script>
