<li class="nav-list nav-item">
    <a class="nav-link js-scroll-trigger text-uppercase" href="#">Gestion</a>
    <ul class="list">
        <li class=""><a href="<?= HOST; ?>manage/superadmins">Administrateur</a></li><hr>
        <li class=""><a href="<?= HOST; ?>manage/activeEntreprises">Entreprise</a></li><hr>
        <li class=""><a href="<?= HOST; ?>manage/activeCandidats">Candidat</a></li><hr>
        <li class=""><a href="<?= HOST; ?>manage/emails_contacts">Contact</a></li><hr>
        <li class="nav-list nav-item nav-sous-list">
            <a class="" href="#">Archives</a>
            <ul class="sous-list">
                <li><a href="<?= HOST; ?>manage/archiveEntreprises">Entreprise</a></li><hr>
                <li><a href="<?= HOST; ?>manage/archiveCandidats">Candidat</a></li>
            </ul>
        </li><hr>
        <li class=""><a href="<?= HOST; ?>manage/historiques">Historique</a></li>
    </ul>
</li>
<li class="nav-list nav-item">
    <a class="nav-link js-scroll-trigger text-uppercase" href="#">Recrutement</a>
    <ul class="list">
        <li><a href="<?= HOST; ?>manage/domaines">Domaine</a></li><hr>
        <li><a href="<?= HOST; ?>manage/personnalites">Personnalité</a></li><hr>
        <li><a href="<?= HOST; ?>manage/contrats">Contrat</a></li><hr>
        <li><a href="<?= HOST; ?>manage/niveaux_experiences">Niveau d'expérience</a></li><hr>
        <li><a href="<?= HOST; ?>manage/niveaux_etudes">Niveau d'étude</a></li>
    </ul>
</li>
