<li class="nav-list nav-item">
    <a class="nav-link js-scroll-trigger text-uppercase" href="#">Mes acitvités</a>
    <ul class="list text-lowercase">
        <li><a href="<?= HOST;?>manage/candidatures">Candidatures envoyées</a></li><hr>
        <li><a href="<?= HOST;?>manage/suggest_offres">Offres suggérées</a></li><hr>
        <li><a href="<?= HOST;?>offres">Offres disponibles</a></li>
    </ul>
</li>
