<li class="nav-list nav-item">
    <a class="nav-link js-scroll-trigger text-uppercase" href="#">Mes acitvités</a>
    <ul class="list text-lowercase">
        <li class="nav-list nav-item nav-sous-list">
		    <a class="" href="#">Offres</a>
		    <ul class="sous-list text-lowercase">
		        <li><a href="<?= HOST; ?>manage/offres">Liste</a></li><hr>
		        <li><a href="<?= HOST; ?>manage/tableau_de_bord-offre">Tableau de bord</a></li>
		    </ul>
		</li><br>
		<li class="nav-list nav-item nav-sous-list">
		    <a class="" href="#">Entretiens</a>
		    <ul class="sous-list text-lowercase">
		        <li><a href="<?= HOST; ?>manage/entretiens">Liste</a></li><hr>
		        <li><a href="<?= HOST; ?>manage/niveaux_entretiens">Niveaux</a></li><hr>
		        <li><a href="<?= HOST; ?>manage/interlocuteurs">Interlocuteurs</a></li>
		    </ul>
		</li>
    </ul>
</li>
<li class="nav-list nav-item">
    <a class="nav-link js-scroll-trigger text-uppercase" href="#">Gestion</a>
    <ul class="list">
        <li class=""><a href="<?= HOST; ?>manage/entreprise_services">Service</a></li><hr>
    </ul>
</li>