<?php
	$url = explode('-', $_GET['page']);
?>
<section class="page-section" id="back-section">
    <div class="container">
      	<div class="row">
        	<div class="col-lg-12">
          		<form id="form" method="POST" action="<?= HOST. "manage/save-" . $url[1];?>" enctype="multipart/form-data" novalidate="novalidate">
	                <?php if ($url[1] == "banque" && !empty($data)): $pageTitle = "Enregistrement d'une banque"; $banque = $data; ?>	            	
				    	<div class="row">
					        <div class="col-lg-12 text-center">
					          	<h5><?= $pageTitle; ?></h5>
					        </div>
				      	</div>
		            	<div class="row">
		            		<div class="col-md-4"></div>
		            		<div class="col-md-4 block-div">
			            		<div class="form-group hidden">
				                  	<input class="form-control" id="idBanque" name="idBanque" type="number" value="<?= $banque->getIdBanque();?>">
				                </div>
				                <div class="form-group">
				                	<label class="label-input">Code banque :</label>
				                  	<input class="form-control focus_activated text-uppercase" id="codeBanque" name="codeBanque" type="text" value="<?= $banque->getCodeBanque();?>" required="required" data-validation-required-message="Veuillez entrer le code banque" data-validation-regex-regex="^[0-9a-zA-Z|éèêëôöîïàùç |'-]*" data-validation-regex-message="Caractères non valide ">
				                  	<p class="help-block text-danger"></p>
				                </div>
				                <div class="form-group">
				                	<label class="label-input">Nom de la banque :</label>
				                  	<input class="form-control focus_activated text-capitalize" id="nomBanque" name="nomBanque" type="text" value="<?= $banque->getNomBanque();?>" required="required" data-validation-required-message="Veuillez entrer le nom de la banque" data-validation-regex-regex="^[0-9a-zA-Z|éèêëôöîïàùç |'-]*" data-validation-regex-message="Caractères non valide ">
				                  	<p class="help-block text-danger"></p>
				                </div>	
				                <div class="form-group">
				                	<label class="label-input">Ville :</label>
				                  	<input class="form-control focus_activated text-capitalize" id="ville" name="ville" type="text" value="<?= $banque->getVille();?>" required="required" data-validation-required-message="Veuillez entrer le ville" data-validation-regex-regex="^[0-9a-zA-Z|éèêëôöîïàùç |'-]*" data-validation-regex-message="Caractères non valide ">
				                  	<p class="help-block text-danger"></p>
				                </div>			                			                
			            	</div>
		            	</div>
		            <?php endif; ?>		            

		            <div class="col-lg-12 text-center">
	                	<div id="success"></div>
	                	<button id="submit" class="btn btn-info btn-xl" type="submit">
	                		Enregistrer
	                	</button>
	                	<a class="btn btn-danger btn-xl" href="<?= $_SERVER['HTTP_REFERER']; ?>">Annuler</a>		                	
	              	</div>
          		</form>
        	</div>
      	</div>
    </div>
</section>

<script src="<?= HOST; ?>../Web/Ressources/js/afficherFormRecrutement.js"></script>
