<style type="text/css" href="<?= HOST; ?>../Web/Ressources/css/plugin/dataTable.bootstrap.css"></style>
<style type="text/css" href="<?= HOST; ?>../Web/Ressources/css/plugin/dataTable.responsive.css"></style>
<?php
	$url = explode("/", $_GET['page']);
	$url = $url[1];

	unset($_SESSION['variable']);
?>

<section class="page-section" id="back-section">
	<div class="container">
		<?php if($url == "banques"): $banques = $data; $pageTitle = "Banques";?>
			<div class="row">
				<div class="col-md-3">
					<a href="<?= HOST . "manage/create-banque";?>" class="btn btn-primary" id="add-btn">
						<i class="fas fa-plus"></i>	Ajouter	        		
		      		</a>
				</div>
				<div class="col-md-6">
					<h4 class="text-center list-title">Liste des banques</h4>
				</div>
			</div>
			<div class="row">
				<table class="table table-stiped table-scroll small-first-col">
					<thead>
						<tr>
							<th>Code banque</th>
							<th>Nom de la banque</th>
							<th>Ville</th>
							<th class="text-center">Action</th>
						</tr>
					</thead>
					<tbody id="tableSearch" class="body-half-screen">
						<?php if(!empty($banques)) : foreach ($banques as $banque): ?>
				        <tr>
				            <td>
				              <?= strtoupper($banque->getCodeBanque()); ?>
				            </td>
				            <td>
				              <?= ucwords($banque->getNomBanque()); ?>
				            </td>
				            <td>
				              <?= ucwords($banque->getVille()); ?>
				            </td>
				            <td class="text-center">
				            	<a href="<?= HOST . "manage/update-banque?idBanque=" . $banque->getIdBanque(); ?>" class="btn btn-warning">
						        	<i class="fas fa-edit">	</i>
						      	</a>
				            	<a href="#" class="btn btn-danger delete" data-toggle="modal" data-target="#deleteModal" data-id="<?= $banque->getIdBanque(); ?>" data-name="<?= $banque->getNomBanque(); ?>" data-url="delete-banque?idBanque=">
				                    <i class="fas fa-trash"></i>
				                </a>
				            </td>
				        </tr>
				        <?php endforeach; ?>
				        <?php endif; ?>
					</tbody>
				</table>
			</div>
		<?php endif ?>

	</div>	
</section>

 <!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center">Confirmation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p id="text-confirmation"></p>
      </div>
      <div class="modal-footer">
        <a id="action-delete" class="btn btn-success">Oui</a>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Non</button>
      </div>
    </div>
  </div>
</div>

<script src="<?= HOST; ?>../Web/Ressources/js/listerModuleEmploye.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/jquery.dataTables.min.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/datatable.js"></script>
<script src="<?= HOST; ?>../Web/Ressources/js/plugin/dataTables.responsive.js"></script>